questions = [
   "What is Python?",
    "What is PEP 8?",
    "What is a variable in Python?",
    "How do you declare a list in Python?",
    "What is a dictionary in Python?",
    "What does len() do?",
    "How do you create a tuple in Python?",
    "What is a function in Python?",
    "What is a lambda function?",
    "What is a loop in Python?",
    "How do you comment code in Python?",
    "What is a module in Python?",
    "How do you import a module?",
    "What is the difference between `==` and `is`?",
    "What does `if __name__ == '__main__':` do?",
    "How do you handle exceptions in Python?",
    "What is a list comprehension?",
    "What is a set in Python?",
    "How do you create a class in Python?",
    "What is inheritance in Python?",
    "What is a constructor in Python?",
    "What is `self` in a class?",
    "What is a decorator?",
    "What is the `pass` statement?",
    "What does `break` do in a loop?",
    "What does `continue` do in a loop?",
    "What is the `with` statement used for?",
    "How do you open a file in Python?",
    "What is a generator in Python?",
    "What does `yield` do?",
    "What is a list slice?",
    "How do you convert a string to an integer?",
    "How do you convert a string to a list?",
    "What is the purpose of `__init__.py`?",
    "What is a virtual environment?",
    "How do you install packages in Python?",
    "What is pip?",
    "How do you check the version of Python?",
    "What does `strip()` do in a string?",
    "How do you concatenate strings?",
    "What is string formatting in Python?",
    "What is a Python package?",
    "What is the difference between `list.append()` and `list.extend()`?",
    "How do you reverse a list?",
    "What is the purpose of `*args` and `**kwargs`?",
    "What is a global variable?",
    "How do you create a constant in Python?",
    "What is the `map()` function?",
    "What is a lambda function used for?",
    "What is the difference between a deep copy and a shallow copy?"
]